name: Build and Publish to NameCheap

on:
  create:
    tags: [ release/** ]

jobs:
  Build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Yarn install 
      run: yarn --cwd ./Web/main install
    - name: Yarn Build
      run: yarn --cwd ./Web/main build
    - uses: actions/upload-artifact@v2
      with:
        name: web-publish
        path: ./Web/main/dist

  Deploy:
    needs: Build-and-publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: gh-pages
    - name: Delete files
      run: ls
    - uses: actions/download-artifact@v2
      with:
        name: web-publish
        path: web-publish
    
    
    


